### ISSUE TITLE
Dependance of obsolete python-setuptools < 74

### ISSUE THREAD

**Issue by Popolon** [wanadev/mozjpeg-lossless-optimization#26] opened 2024-11-19 21:46 UTC
The current code of mozjpeg-losless-optimization has python-setuptools < 74 as requirement.

Current release of setuptools is 75, this is the version used on ArchLinux, so it's a blocker to have it still compiled or upgraded on at least this Linux distribution.

**Comment by flozz** [comment] 2024-11-21 10:58
Setuptools 74 & 75 break the Windows build... I am trying something to limit the version only on this platform

**Comment by flozz** [comment] 2024-11-22 09:00
I found a solution to our problem. I will release a new version of the lib in few days. :)

----

Notes if someone is searching for a solution.

I improved the way I search for the MSBuild location:

```python
def _find_msbuild(plat_spec="x64"):
    from setuptools import msvc

    if hasattr(msvc, "msvc14_get_vc_env"):
        vc_env = msvc.msvc14_get_vc_env(plat_spec)
        if "vsinstalldir" in vc_env:
            msbuild_path = os.path.join(
                vc_env["vsinstalldir"], "MSBuild", "Current", "Bin", "MSBuild.exe"
            )
            if os.path.isfile(msbuild_path):
                return msbuild_path

    for path in msvc.EnvironmentInfo(plat_spec).VCTools:
        if "\\VC\\" not in path:
            continue
        msbuild_path = os.path.join(
            path[: path.index("\\VC\\")], "MSBuild", "Current", "Bin", "MSBuild.exe"
        )
        if os.path.isfile(msbuild_path):
            return msbuild_path

    raise Exception("Unable to find any Visual Studio installation")
```

But I still have an issue with older PyPy versions on Windows. The problem is related to CFFI and newer setuptools versions. It is fixed in newer releases of CFFI, but as PyPy embed its own CFFI version, there is no fix for older PyPy versions so we have to pin the setuptools version for this implementation.

Here is how to pin setuptools version only for pypy on windows:

```toml
[build-system]
requires = [
    "setuptools",
    "setuptools<74; platform_system=='Windows' and implementation_name=='pypy'",
]
build-backend = "setuptools.build_meta"
```

More reading:

* https://github.com/python-cffi/cffi/pull/118
* https://github.com/pypy/pypy/issues/5027

**Comment by flozz** [comment] 2024-11-22 13:58
Finally I was able to release this today. The v1.1.5 fixes the issue, the build of the packages is in progress :)

https://github.com/wanadev/mozjpeg-lossless-optimization/releases/tag/v1.1.5

**Closed by flozz** 2024-11-22 13:58 UTC

**Comment by Popolon** [comment] 2024-11-24 13:51
Sadly an header is missing in 1.1.5, see  #27
